INSERT OR IGNORE INTO hardware_catalog
    (category, manufacturer, name, platform, chipset, form_factor, memory, search_terms, specs_json)
VALUES
    ('Processors', 'AMD', 'Ryzen 9 9950X3D', 'AMD AM5', 'Ryzen 9000 X3D', 'Desktop CPU', 'DDR5', '16-core gaming 3D V-Cache', '{"cores":16,"threads":32}'),
    ('Processors', 'AMD', 'Ryzen 9 9950X', 'AMD AM5', 'Ryzen 9000', 'Desktop CPU', 'DDR5', '16-core Zen 5', '{"cores":16,"threads":32}'),
    ('Processors', 'AMD', 'Ryzen 9 9900X', 'AMD AM5', 'Ryzen 9000', 'Desktop CPU', 'DDR5', '12-core Zen 5', '{"cores":12,"threads":24}'),
    ('Processors', 'AMD', 'Ryzen 7 9800X3D', 'AMD AM5', 'Ryzen 9000 X3D', 'Desktop CPU', 'DDR5', '8-core gaming 3D V-Cache', '{"cores":8,"threads":16}'),
    ('Processors', 'AMD', 'Ryzen 7 9700X', 'AMD AM5', 'Ryzen 9000', 'Desktop CPU', 'DDR5', '8-core Zen 5', '{"cores":8,"threads":16}'),
    ('Processors', 'AMD', 'Ryzen 5 9600X', 'AMD AM5', 'Ryzen 9000', 'Desktop CPU', 'DDR5', '6-core Zen 5', '{"cores":6,"threads":12}'),
    ('Processors', 'AMD', 'Ryzen 7 7800X3D', 'AMD AM5', 'Ryzen 7000 X3D', 'Desktop CPU', 'DDR5', '8-core gaming 3D V-Cache', '{"cores":8,"threads":16}'),
    ('Processors', 'AMD', 'Ryzen 5 7600', 'AMD AM5', 'Ryzen 7000', 'Desktop CPU', 'DDR5', '6-core Zen 4', '{"cores":6,"threads":12}'),
    ('Processors', 'Intel', 'Core Ultra 9 285K', 'Intel LGA1851', 'Core Ultra 200K', 'Desktop CPU', 'DDR5', '24-core Arrow Lake', '{"cores":24,"threads":24}'),
    ('Processors', 'Intel', 'Core Ultra 7 265K', 'Intel LGA1851', 'Core Ultra 200K', 'Desktop CPU', 'DDR5', '20-core Arrow Lake', '{"cores":20,"threads":20}'),
    ('Processors', 'Intel', 'Core Ultra 5 245K', 'Intel LGA1851', 'Core Ultra 200K', 'Desktop CPU', 'DDR5', '14-core Arrow Lake', '{"cores":14,"threads":14}'),
    ('Processors', 'Intel', 'Core i9-14900K', 'Intel LGA1700', '14th Gen Core', 'Desktop CPU', 'DDR4 or DDR5', '24-core Raptor Lake Refresh', '{"cores":24,"threads":32}'),
    ('Processors', 'Intel', 'Core i7-14700K', 'Intel LGA1700', '14th Gen Core', 'Desktop CPU', 'DDR4 or DDR5', '20-core Raptor Lake Refresh', '{"cores":20,"threads":28}'),
    ('Processors', 'Intel', 'Core i5-14600K', 'Intel LGA1700', '14th Gen Core', 'Desktop CPU', 'DDR4 or DDR5', '14-core Raptor Lake Refresh', '{"cores":14,"threads":20}'),

    ('Memory', 'Corsair', 'Vengeance 32GB (2x16GB) DDR5-6000 CL30', 'Desktop DIMM', 'DDR5', 'UDIMM kit', '32GB', '6000 MT/s CL30 EXPO XMP', '{"capacity":"2x16GB","speed":"6000 MT/s","latency":"CL30"}'),
    ('Memory', 'Corsair', 'Vengeance 64GB (2x32GB) DDR5-6000', 'Desktop DIMM', 'DDR5', 'UDIMM kit', '64GB', '6000 MT/s EXPO XMP', '{"capacity":"2x32GB","speed":"6000 MT/s"}'),
    ('Memory', 'G.Skill', 'Flare X5 32GB (2x16GB) DDR5-6000 CL30', 'Desktop DIMM', 'DDR5', 'UDIMM kit', '32GB', '6000 MT/s CL30 AMD EXPO', '{"capacity":"2x16GB","speed":"6000 MT/s","latency":"CL30"}'),
    ('Memory', 'G.Skill', 'Trident Z5 Neo RGB 32GB DDR5-6000', 'Desktop DIMM', 'DDR5', 'RGB UDIMM kit', '32GB', '6000 MT/s AMD EXPO', '{"capacity":"2x16GB","speed":"6000 MT/s"}'),
    ('Memory', 'Kingston', 'FURY Beast 32GB (2x16GB) DDR5-6000', 'Desktop DIMM', 'DDR5', 'UDIMM kit', '32GB', '6000 MT/s EXPO XMP', '{"capacity":"2x16GB","speed":"6000 MT/s"}'),
    ('Memory', 'TeamGroup', 'T-Create Expert 32GB (2x16GB) DDR5-6000', 'Desktop DIMM', 'DDR5', 'UDIMM kit', '32GB', '6000 MT/s EXPO XMP', '{"capacity":"2x16GB","speed":"6000 MT/s"}'),
    ('Memory', 'Crucial', 'Pro 32GB (2x16GB) DDR5-6000', 'Desktop DIMM', 'DDR5', 'UDIMM kit', '32GB', '6000 MT/s EXPO XMP', '{"capacity":"2x16GB","speed":"6000 MT/s"}'),
    ('Memory', 'Corsair', 'Vengeance LPX 32GB (2x16GB) DDR4-3600', 'Desktop DIMM', 'DDR4', 'UDIMM kit', '32GB', '3600 MT/s CL18 XMP', '{"capacity":"2x16GB","speed":"3600 MT/s","latency":"CL18"}'),
    ('Memory', 'Kingston', 'FURY Beast 32GB (2x16GB) DDR4-3200', 'Desktop DIMM', 'DDR4', 'UDIMM kit', '32GB', '3200 MT/s XMP', '{"capacity":"2x16GB","speed":"3200 MT/s"}'),
    ('Memory', 'G.Skill', 'Ripjaws S5 32GB (2x16GB) DDR5-6000', 'Desktop DIMM', 'DDR5', 'Low-profile UDIMM kit', '32GB', '6000 MT/s EXPO XMP', '{"capacity":"2x16GB","speed":"6000 MT/s"}'),

    ('Storage', 'Samsung', '990 PRO 1TB', 'NVMe PCIe 4.0', 'Samsung 990 PRO', 'M.2 2280', '1TB', 'SSD TLC cache', '{"interface":"PCIe 4.0 x4","capacity":"1TB"}'),
    ('Storage', 'Samsung', '990 PRO 2TB', 'NVMe PCIe 4.0', 'Samsung 990 PRO', 'M.2 2280', '2TB', 'SSD TLC cache', '{"interface":"PCIe 4.0 x4","capacity":"2TB"}'),
    ('Storage', 'Western Digital', 'WD Black SN850X 1TB', 'NVMe PCIe 4.0', 'WD Black', 'M.2 2280', '1TB', 'gaming SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"1TB"}'),
    ('Storage', 'Western Digital', 'WD Black SN850X 2TB', 'NVMe PCIe 4.0', 'WD Black', 'M.2 2280', '2TB', 'gaming SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"2TB"}'),
    ('Storage', 'Western Digital', 'WD Black SN850X 4TB', 'NVMe PCIe 4.0', 'WD Black', 'M.2 2280', '4TB', 'gaming SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"4TB"}'),
    ('Storage', 'Crucial', 'T500 1TB', 'NVMe PCIe 4.0', 'Crucial T500', 'M.2 2280', '1TB', 'SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"1TB"}'),
    ('Storage', 'Crucial', 'T500 2TB', 'NVMe PCIe 4.0', 'Crucial T500', 'M.2 2280', '2TB', 'SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"2TB"}'),
    ('Storage', 'Kingston', 'KC3000 1TB', 'NVMe PCIe 4.0', 'Kingston KC3000', 'M.2 2280', '1TB', 'SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"1TB"}'),
    ('Storage', 'Kingston', 'KC3000 2TB', 'NVMe PCIe 4.0', 'Kingston KC3000', 'M.2 2280', '2TB', 'SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"2TB"}'),
    ('Storage', 'Lexar', 'NM790 1TB', 'NVMe PCIe 4.0', 'Lexar NM790', 'M.2 2280', '1TB', 'SSD DRAM-less', '{"interface":"PCIe 4.0 x4","capacity":"1TB"}'),
    ('Storage', 'Lexar', 'NM790 2TB', 'NVMe PCIe 4.0', 'Lexar NM790', 'M.2 2280', '2TB', 'SSD DRAM-less', '{"interface":"PCIe 4.0 x4","capacity":"2TB"}'),
    ('Storage', 'Samsung', '870 EVO 1TB', 'SATA III', 'Samsung 870 EVO', '2.5-inch SATA', '1TB', 'SSD', '{"interface":"SATA 6 Gb/s","capacity":"1TB"}'),
    ('Storage', 'Seagate', 'FireCuda 530 2TB', 'NVMe PCIe 4.0', 'FireCuda 530', 'M.2 2280', '2TB', 'SSD TLC', '{"interface":"PCIe 4.0 x4","capacity":"2TB"}'),

    ('Power Supplies', 'Corsair', 'RM850x 850W', 'ATX 3.1', '80 PLUS Gold', 'ATX modular PSU', '850W', 'fully modular PCIe 5.1', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'Corsair', 'RM750e 750W', 'ATX 3.1', '80 PLUS Gold', 'ATX modular PSU', '750W', 'fully modular PCIe 5.1', '{"wattage":"750W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'Corsair', 'RM1000x 1000W', 'ATX 3.1', '80 PLUS Gold', 'ATX modular PSU', '1000W', 'fully modular PCIe 5.1', '{"wattage":"1000W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'Seasonic', 'FOCUS GX-850', 'ATX 3.0', '80 PLUS Gold', 'ATX modular PSU', '850W', 'fully modular', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'be quiet!', 'Pure Power 12 M 850W', 'ATX 3.0', '80 PLUS Gold', 'ATX modular PSU', '850W', 'PCIe 5.0 modular', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'MSI', 'MAG A850GL PCIE5', 'ATX 3.0', '80 PLUS Gold', 'ATX modular PSU', '850W', 'PCIe 5.0 modular', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'NZXT', 'C850 Gold ATX 3.1', 'ATX 3.1', '80 PLUS Gold', 'ATX modular PSU', '850W', 'PCIe 5.1 modular', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'Thermaltake', 'Toughpower GF A3 850W', 'ATX 3.0', '80 PLUS Gold', 'ATX modular PSU', '850W', 'PCIe 5.0 modular', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'Cooler Master', 'MWE Gold 850 V2', 'ATX 2.52', '80 PLUS Gold', 'ATX modular PSU', '850W', 'fully modular', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),
    ('Power Supplies', 'Fractal Design', 'Ion Gold 850W', 'ATX 2.52', '80 PLUS Gold', 'ATX modular PSU', '850W', 'fully modular', '{"wattage":"850W","efficiency":"80 PLUS Gold"}'),

    ('PC Cases', 'Corsair', '4000D Airflow', 'ATX', 'Airflow mid-tower', 'Mid tower', '', 'tempered glass mesh', '{"front_io":"USB-C, USB-A","max_gpu_length":"360mm"}'),
    ('PC Cases', 'Corsair', '5000D Airflow', 'ATX', 'Airflow mid-tower', 'Mid tower', '', 'tempered glass mesh', '{"front_io":"USB-C, USB-A"}'),
    ('PC Cases', 'Corsair', '3500X ARGB', 'ATX', 'Panoramic glass', 'Mid tower', '', 'wraparound glass RGB', '{"included_fans":3}'),
    ('PC Cases', 'Fractal Design', 'North', 'ATX', 'Mesh or glass front', 'Mid tower', '', 'wood front walnut oak', '{"front_io":"USB-C, USB-A"}'),
    ('PC Cases', 'Fractal Design', 'Torrent', 'ATX', 'High-airflow tower', 'Mid tower', '', 'mesh gaming airflow', '{"included_fans":5}'),
    ('PC Cases', 'Fractal Design', 'Meshify 2 Compact', 'ATX', 'Mesh front', 'Mid tower', '', 'airflow tempered glass', '{"front_io":"USB-C, USB-A"}'),
    ('PC Cases', 'NZXT', 'H5 Flow', 'ATX', 'Airflow mid-tower', 'Mid tower', '', 'mesh front tempered glass', '{"front_io":"USB-C, USB-A"}'),
    ('PC Cases', 'NZXT', 'H7 Flow', 'ATX', 'Airflow mid-tower', 'Mid tower', '', 'mesh front tempered glass', '{"front_io":"USB-C, USB-A"}'),
    ('PC Cases', 'Lian Li', 'LANCOOL 216', 'ATX', 'High-airflow mid-tower', 'Mid tower', '', 'mesh front ARGB', '{"included_fans":3}'),
    ('PC Cases', 'Lian Li', 'O11 Dynamic EVO', 'ATX', 'Dual-chamber glass', 'Mid tower', '', 'panoramic tempered glass', '{"fan_positions":10}'),
    ('PC Cases', 'Phanteks', 'XT Pro Ultra', 'ATX', 'High-airflow mid-tower', 'Mid tower', '', 'mesh front D-RGB', '{"included_fans":4}'),
    ('PC Cases', 'Montech', 'AIR 903 MAX', 'ATX', 'Airflow mid-tower', 'Mid tower', '', 'mesh front ARGB', '{"included_fans":4}'),

    ('CPU Coolers', 'Thermalright', 'Peerless Assassin 120 SE', 'AMD AM5 Intel LGA1851/1700', 'Dual-tower air', '120mm dual fan', '', 'air cooler heatsink', '{"cooling":"dual tower","fans":2}'),
    ('CPU Coolers', 'Thermalright', 'Phantom Spirit 120 SE', 'AMD AM5 Intel LGA1851/1700', 'Dual-tower air', '120mm dual fan', '', 'air cooler heatsink', '{"cooling":"dual tower","fans":2}'),
    ('CPU Coolers', 'Noctua', 'NH-D15 G2', 'AMD AM5 Intel LGA1851/1700', 'Dual-tower air', '140mm dual fan', '', 'air cooler heatsink', '{"cooling":"dual tower","fans":2}'),
    ('CPU Coolers', 'DeepCool', 'AK620', 'AMD AM5 Intel LGA1851/1700', 'Dual-tower air', '120mm dual fan', '', 'air cooler heatsink', '{"cooling":"dual tower","fans":2}'),
    ('CPU Coolers', 'ARCTIC', 'Liquid Freezer III 360', 'AMD AM5 Intel LGA1851/1700', 'AIO liquid cooler', '360mm radiator', '', 'liquid cooler 3 fan', '{"radiator":"360mm","fans":3}'),
    ('CPU Coolers', 'Corsair', 'iCUE H150i ELITE CAPELLIX XT', 'AMD AM5 Intel LGA1851/1700', 'AIO liquid cooler', '360mm radiator', '', 'liquid cooler RGB', '{"radiator":"360mm","fans":3}'),
    ('CPU Coolers', 'be quiet!', 'Dark Rock Pro 5', 'AMD AM5 Intel LGA1851/1700', 'Dual-tower air', '135mm dual fan', '', 'air cooler silent', '{"cooling":"dual tower","fans":2}'),
    ('CPU Coolers', 'Cooler Master', 'MasterLiquid 360 Atmos', 'AMD AM5 Intel LGA1851/1700', 'AIO liquid cooler', '360mm radiator', '', 'liquid cooler', '{"radiator":"360mm","fans":3}'),
    ('CPU Coolers', 'NZXT', 'Kraken 360 RGB', 'AMD AM5 Intel LGA1851/1700', 'AIO liquid cooler', '360mm radiator', '', 'liquid cooler LCD RGB', '{"radiator":"360mm","fans":3}'),

    ('Case Fans', 'ARCTIC', 'P12 PWM PST', 'PWM 4-pin', 'Pressure-optimized fan', '120mm', '', 'case fan daisy-chain', '{"size":"120mm","bearing":"fluid dynamic"}'),
    ('Case Fans', 'ARCTIC', 'P14 PWM PST', 'PWM 4-pin', 'Pressure-optimized fan', '140mm', '', 'case fan daisy-chain', '{"size":"140mm","bearing":"fluid dynamic"}'),
    ('Case Fans', 'Noctua', 'NF-A12x25 PWM', 'PWM 4-pin', 'Premium airflow fan', '120mm', '', 'case fan quiet', '{"size":"120mm","bearing":"SSO2"}'),
    ('Case Fans', 'be quiet!', 'Silent Wings 4 120mm PWM', 'PWM 4-pin', 'Quiet airflow fan', '120mm', '', 'case fan silent', '{"size":"120mm"}'),
    ('Case Fans', 'Lian Li', 'UNI FAN SL-INF 120', 'PWM 4-pin', 'Daisy-chain RGB fan', '120mm', '', 'case fan infinity mirror RGB', '{"size":"120mm","lighting":"ARGB"}'),
    ('Case Fans', 'Phanteks', 'T30-120', 'PWM 4-pin', 'High-performance fan', '120mm', '', 'case fan high static pressure', '{"size":"120mm","thickness":"30mm"}'),
    ('Case Fans', 'Corsair', 'iCUE AF120 RGB ELITE', 'PWM 4-pin', 'RGB airflow fan', '120mm', '', 'case fan RGB', '{"size":"120mm","lighting":"ARGB"}'),

    ('Monitors', 'LG', 'UltraGear 27GS95QE-B', 'DisplayPort HDMI', 'OLED', '27-inch QHD', '2560x1440 240Hz', 'gaming monitor 0.03ms', '{"resolution":"2560x1440","refresh":"240Hz","panel":"OLED"}'),
    ('Monitors', 'ASUS', 'ROG Swift OLED PG27AQDM', 'DisplayPort HDMI', 'OLED', '27-inch QHD', '2560x1440 240Hz', 'gaming monitor', '{"resolution":"2560x1440","refresh":"240Hz","panel":"WOLED"}'),
    ('Monitors', 'ASUS', 'ROG Swift OLED PG32UCDM', 'DisplayPort HDMI USB-C', 'QD-OLED', '32-inch 4K', '3840x2160 240Hz', 'gaming monitor', '{"resolution":"3840x2160","refresh":"240Hz","panel":"QD-OLED"}'),
    ('Monitors', 'Samsung', 'Odyssey OLED G8 G80SD', 'DisplayPort HDMI', 'QD-OLED', '32-inch 4K', '3840x2160 240Hz', 'gaming monitor smart', '{"resolution":"3840x2160","refresh":"240Hz","panel":"QD-OLED"}'),
    ('Monitors', 'Alienware', 'AW2725DF', 'DisplayPort HDMI', 'QD-OLED', '27-inch QHD', '2560x1440 360Hz', 'gaming monitor', '{"resolution":"2560x1440","refresh":"360Hz","panel":"QD-OLED"}'),
    ('Monitors', 'Alienware', 'AW3225QF', 'DisplayPort HDMI', 'QD-OLED', '32-inch curved 4K', '3840x2160 240Hz', 'gaming monitor', '{"resolution":"3840x2160","refresh":"240Hz","panel":"QD-OLED"}'),
    ('Monitors', 'Gigabyte', 'M27Q X', 'DisplayPort HDMI USB-C', 'SuperSpeed IPS', '27-inch QHD', '2560x1440 240Hz', 'gaming monitor KVM', '{"resolution":"2560x1440","refresh":"240Hz","panel":"IPS"}'),
    ('Monitors', 'Dell', 'G2724D', 'DisplayPort HDMI', 'Fast IPS', '27-inch QHD', '2560x1440 165Hz', 'gaming monitor', '{"resolution":"2560x1440","refresh":"165Hz","panel":"IPS"}'),
    ('Monitors', 'AOC', 'Q27G3XMN', 'DisplayPort HDMI', 'Mini LED VA', '27-inch QHD', '2560x1440 180Hz', 'gaming monitor HDR', '{"resolution":"2560x1440","refresh":"180Hz","panel":"Mini LED VA"}'),
    ('Monitors', 'MSI', 'MPG 271QRX QD-OLED', 'DisplayPort HDMI USB-C', 'QD-OLED', '27-inch QHD', '2560x1440 360Hz', 'gaming monitor', '{"resolution":"2560x1440","refresh":"360Hz","panel":"QD-OLED"}'),
    ('Monitors', 'ASUS', 'TUF Gaming VG27AQML1A', 'DisplayPort HDMI', 'Fast IPS', '27-inch QHD', '2560x1440 260Hz', 'gaming monitor', '{"resolution":"2560x1440","refresh":"260Hz","panel":"IPS"}'),
    ('Monitors', 'BenQ', 'MOBIUZ EX2710Q', 'DisplayPort HDMI', 'IPS', '27-inch QHD', '2560x1440 165Hz', 'gaming monitor speakers', '{"resolution":"2560x1440","refresh":"165Hz","panel":"IPS"}'),

    ('Keyboards', 'Keychron', 'Q1 Max', 'USB Bluetooth 2.4GHz', 'Mechanical hot-swap', '75% layout', '', 'wireless keyboard QMK VIA', '{"layout":"75%","switches":"hot-swappable"}'),
    ('Keyboards', 'Keychron', 'V1 Max', 'USB Bluetooth 2.4GHz', 'Mechanical hot-swap', '75% layout', '', 'wireless keyboard QMK VIA', '{"layout":"75%","switches":"hot-swappable"}'),
    ('Keyboards', 'Keychron', 'K2 Pro', 'USB Bluetooth', 'Mechanical', '75% layout', '', 'wireless keyboard Mac Windows', '{"layout":"75%"}'),
    ('Keyboards', 'Wooting', '80HE', 'USB wired', 'Lekker Hall Effect', 'TKL layout', '', 'rapid trigger analog gaming keyboard', '{"layout":"TKL","switches":"Hall Effect"}'),
    ('Keyboards', 'Wooting', '60HE+', 'USB wired', 'Lekker Hall Effect', '60% layout', '', 'rapid trigger analog gaming keyboard', '{"layout":"60%","switches":"Hall Effect"}'),
    ('Keyboards', 'Logitech', 'G PRO X TKL LIGHTSPEED', 'USB 2.4GHz wireless', 'GX mechanical', 'TKL layout', '', 'gaming keyboard wireless', '{"layout":"TKL"}'),
    ('Keyboards', 'Logitech', 'G915 X LIGHTSPEED', 'USB Bluetooth 2.4GHz', 'Low-profile mechanical', 'Full-size layout', '', 'wireless gaming keyboard RGB', '{"layout":"Full-size"}'),
    ('Keyboards', 'Razer', 'Huntsman V3 Pro TKL', 'USB wired', 'Analog optical', 'TKL layout', '', 'rapid trigger gaming keyboard', '{"layout":"TKL","switches":"Analog optical"}'),
    ('Keyboards', 'Razer', 'BlackWidow V4 75%', 'USB wired', 'Mechanical hot-swap', '75% layout', '', 'gaming keyboard RGB', '{"layout":"75%","switches":"hot-swappable"}'),
    ('Keyboards', 'SteelSeries', 'Apex Pro TKL Gen 3', 'USB wired', 'OmniPoint Hall Effect', 'TKL layout', '', 'rapid trigger gaming keyboard OLED', '{"layout":"TKL","switches":"Hall Effect"}'),
    ('Keyboards', 'Corsair', 'K70 CORE', 'USB wired', 'Corsair MLX mechanical', 'Full-size layout', '', 'gaming keyboard RGB', '{"layout":"Full-size"}'),

    ('Mice', 'Logitech', 'G PRO X SUPERLIGHT 2', 'USB 2.4GHz wireless', 'HERO 2 sensor', 'Gaming mouse', '', 'lightweight esports mouse', '{"weight":"60g","sensor":"HERO 2"}'),
    ('Mice', 'Logitech', 'G502 X LIGHTSPEED', 'USB 2.4GHz wireless', 'HERO 25K sensor', 'Ergonomic gaming mouse', '', 'wireless programmable buttons', '{"sensor":"HERO 25K","buttons":13}'),
    ('Mice', 'Logitech', 'MX Master 3S', 'Bluetooth USB receiver', 'Darkfield sensor', 'Productivity mouse', '', 'wireless office mouse scroll wheel', '{"sensor":"8000 DPI","buttons":7}'),
    ('Mice', 'Razer', 'Viper V3 Pro', 'USB 2.4GHz wireless', 'Focus Pro 35K sensor', 'Esports gaming mouse', '', 'lightweight wireless', '{"weight":"54g","sensor":"Focus Pro 35K"}'),
    ('Mice', 'Razer', 'DeathAdder V3 Pro', 'USB 2.4GHz wireless', 'Focus Pro 30K sensor', 'Ergonomic gaming mouse', '', 'wireless lightweight', '{"weight":"63g","sensor":"Focus Pro 30K"}'),
    ('Mice', 'Razer', 'Basilisk V3 Pro', 'USB Bluetooth 2.4GHz', 'Focus Pro 30K sensor', 'Ergonomic gaming mouse', '', 'wireless RGB programmable', '{"sensor":"Focus Pro 30K","buttons":11}'),
    ('Mice', 'SteelSeries', 'Aerox 5 Wireless', 'USB Bluetooth 2.4GHz', 'TrueMove Air sensor', 'Gaming mouse', '', 'wireless lightweight honeycomb', '{"weight":"74g","buttons":9}'),
    ('Mice', 'Corsair', 'M75 AIR WIRELESS', 'USB 2.4GHz Bluetooth', 'Marksman 26K sensor', 'Gaming mouse', '', 'wireless lightweight', '{"weight":"60g","sensor":"Marksman 26K"}'),
    ('Mice', 'Pulsar', 'X2V2 Wireless', 'USB 2.4GHz wireless', 'PAW3395 sensor', 'Symmetrical gaming mouse', '', 'lightweight esports', '{"weight":"53g","sensor":"PAW3395"}'),
    ('Mice', 'Endgame Gear', 'XM2we', 'USB 2.4GHz wireless', 'PixArt PAW3370 sensor', 'Ergonomic gaming mouse', '', 'wireless esports', '{"weight":"63g","sensor":"PAW3370"}'),
    ('Mice', 'Logitech', 'G305 LIGHTSPEED', 'USB 2.4GHz wireless', 'HERO sensor', 'Gaming mouse', '', 'wireless budget', '{"sensor":"HERO","buttons":6}'),

    ('Headphones & Headsets', 'SteelSeries', 'Arctis Nova Pro Wireless', 'USB Bluetooth 2.4GHz', 'Active noise cancellation', 'Over-ear gaming headset', '', 'wireless PC PS5 Xbox', '{"audio":"ANC","connection":"dual wireless"}'),
    ('Headphones & Headsets', 'SteelSeries', 'Arctis Nova 7 Wireless', 'USB Bluetooth 2.4GHz', 'Neodymium drivers', 'Over-ear gaming headset', '', 'wireless PC PS5 Xbox', '{"connection":"dual wireless"}'),
    ('Headphones & Headsets', 'HyperX', 'Cloud III Wireless', 'USB 2.4GHz wireless', '53mm drivers', 'Over-ear gaming headset', '', 'wireless PC PlayStation', '{"driver":"53mm","connection":"2.4GHz"}'),
    ('Headphones & Headsets', 'Logitech', 'G PRO X 2 LIGHTSPEED', 'USB Bluetooth 2.4GHz', 'Graphene drivers', 'Over-ear gaming headset', '', 'wireless gaming microphone', '{"driver":"50mm graphene"}'),
    ('Headphones & Headsets', 'Audeze', 'Maxwell Wireless', 'USB Bluetooth 2.4GHz', 'Planar magnetic', 'Over-ear gaming headset', '', 'wireless PC PlayStation Xbox', '{"driver":"planar magnetic"}'),
    ('Headphones & Headsets', 'Razer', 'BlackShark V2 Pro (2023)', 'USB 2.4GHz wireless', 'TriForce Titanium 50mm', 'Over-ear gaming headset', '', 'wireless esports microphone', '{"driver":"50mm"}'),
    ('Headphones & Headsets', 'Corsair', 'HS80 MAX Wireless', 'USB Bluetooth 2.4GHz', 'Dolby Atmos', 'Over-ear gaming headset', '', 'wireless PC PlayStation', '{"audio":"Dolby Atmos"}'),
    ('Headphones & Headsets', 'Sony', 'WH-1000XM5', 'Bluetooth wireless', 'Active noise cancellation', 'Over-ear headphones', '', 'wireless ANC travel', '{"audio":"ANC"}'),
    ('Headphones & Headsets', 'Bose', 'QuietComfort Ultra Headphones', 'Bluetooth wireless', 'Active noise cancellation', 'Over-ear headphones', '', 'wireless ANC spatial audio', '{"audio":"ANC spatial audio"}'),
    ('Headphones & Headsets', 'Sennheiser', 'HD 560S', 'Wired 3.5mm', 'Open-back dynamic', 'Over-ear headphones', '', 'wired audiophile reference', '{"impedance":"120 ohm","design":"open-back"}'),
    ('Headphones & Headsets', 'beyerdynamic', 'DT 770 PRO 80 Ohm', 'Wired 3.5mm', 'Closed-back dynamic', 'Over-ear headphones', '', 'studio monitoring wired', '{"impedance":"80 ohm","design":"closed-back"}'),

    ('Networking', 'ASUS', 'PCE-AXE59BT', 'PCIe Wi-Fi 6E Bluetooth', '802.11ax', 'PCIe adapter', '', 'wireless network card tri-band', '{"wifi":"Wi-Fi 6E","bluetooth":"5.2"}'),
    ('Networking', 'TP-Link', 'Archer TXE75E', 'PCIe Wi-Fi 6E Bluetooth', '802.11ax', 'PCIe adapter', '', 'wireless network card tri-band', '{"wifi":"Wi-Fi 6E","bluetooth":"5.2"}'),
    ('Networking', 'TP-Link', 'Archer TBE550E', 'PCIe Wi-Fi 7 Bluetooth', '802.11be', 'PCIe adapter', '', 'wireless network card tri-band', '{"wifi":"Wi-Fi 7","bluetooth":"5.4"}'),
    ('Networking', 'TP-Link', 'TX401 10G', 'PCIe Ethernet', '10 Gigabit Ethernet', 'PCIe adapter', '', 'network card RJ45', '{"ethernet":"10GbE"}'),
    ('Networking', 'ASUS', 'XG-C100C', 'PCIe Ethernet', '10 Gigabit Ethernet', 'PCIe adapter', '', 'network card RJ45', '{"ethernet":"10GbE"}'),
    ('Networking', 'Intel', 'Wi-Fi 6E AX210 M.2 Kit', 'M.2 Wi-Fi 6E Bluetooth', '802.11ax', 'M.2 adapter kit', '', 'wireless network card tri-band', '{"wifi":"Wi-Fi 6E","bluetooth":"5.3"}'),
    ('Networking', 'TP-Link', 'Archer TX3000E', 'PCIe Wi-Fi 6 Bluetooth', '802.11ax', 'PCIe adapter', '', 'wireless network card dual-band', '{"wifi":"Wi-Fi 6","bluetooth":"5.0"}'),
    ('Networking', 'TP-Link', 'Archer T4E', 'PCIe Wi-Fi 5', '802.11ac', 'PCIe adapter', '', 'wireless network card dual-band', '{"wifi":"Wi-Fi 5"}'),

    ('Thermal Paste', 'ARCTIC', 'MX-6 4g', 'Thermal compound', 'Non-conductive paste', 'CPU thermal paste', '4g', 'thermal interface material TIM', '{"weight":"4g","conductive":false}'),
    ('Thermal Paste', 'ARCTIC', 'MX-4 4g', 'Thermal compound', 'Carbon micro-particle paste', 'CPU thermal paste', '4g', 'thermal interface material TIM', '{"weight":"4g","conductive":false}'),
    ('Thermal Paste', 'Noctua', 'NT-H2 3.5g', 'Thermal compound', 'Hybrid thermal paste', 'CPU thermal paste', '3.5g', 'thermal interface material TIM', '{"weight":"3.5g","conductive":false}'),
    ('Thermal Paste', 'Thermal Grizzly', 'Kryonaut 1g', 'Thermal compound', 'High-performance paste', 'CPU thermal paste', '1g', 'thermal interface material TIM', '{"weight":"1g","conductive":false}'),
    ('Thermal Paste', 'Thermalright', 'TF7 2g', 'Thermal compound', 'Thermal paste', 'CPU thermal paste', '2g', 'thermal interface material TIM', '{"weight":"2g","conductive":false}');
